# Generated by Django 3.2.2 on 2021-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211129_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='answer_sheet',
            field=models.FileField(default='sample.pdf', upload_to='student_files'),
        ),
    ]
