# Generated by Django 3.2.2 on 2021-12-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20211202_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default=100, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
