# Generated by Django 3.2.2 on 2022-01-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
